// 1. MUST FOLLOW RULES — PAGE 1. DO NOT REMOVE OR MODIFY THIS TOP COMMENT.
// ANY CODE CHANGE MUST KEEP IT AT THE TOP. KEEP CODE ULTRA-COMPACT. DO NOT ADD EMPTY LINES.
// REDUCE LINE COUNT AGGRESSIVELY: ~100 LINES → ~30 LINES WHEN SAFE. KEEP 100% LOGIC & FUNCTIONALITY.
import express from "express";
import dotenv from "dotenv";
import cors from "cors";
import path from "path";
import {fileURLToPath} from "url";
import http from "http";
import {Server} from "socket.io";
import {connectDB} from "./config/db.js";
import {createAdminUser} from "./config/createAdmin.js";
import authRoutes from "./routes/auth.routes.js";
import userRoutes from "./routes/user.routes.js";
import adminUserRoutes from "./routes/admin.user.routes.js";
import reportRoutes from "./routes/report.routes.js";
import chatRoutes from "./routes/chat.routes.js";
import carBrandRoutes from "./routes/car/brand/car.brand.routes.js";
import carModelRoutes from "./routes/car/model/car.model.routes.js";
import carVariantRoutes from "./routes/car/variant/car.variant.routes.js";
import bikeBrandRoutes from "./routes/bike/brand/bike.brand.routes.js";
import bikeModelRoutes from "./routes/bike/model/bike.model.routes.js";
import bikeVariantRoutes from "./routes/bike/variant/bike.variant.routes.js";
import mobileBrandRoutes from "./routes/electronics/mobile/mobile_brand.routes.js";
import pcBrandRoutes from "./routes/electronics/pc/pc_brand.routes.js";
import laptopBrandRoutes from "./routes/electronics/laptop/laptop_brand.routes.js";
import userElectronicsRoutes from "./routes/electronics/user.electronics.routes.js";
import adminElectronicsRoutes from "./routes/electronics/admin.electronics.routes.js";
import userCarRoutes from "./routes/car/user.car.routes.js";
import adminCarRoutes from "./routes/car/admin.car.routes.js";
import bikeRoutes from "./routes/bike/user.bike.routes.js";
import adminBikeRoutes from "./routes/bike/admin.bike.routes.js";
import oldSpareRoutes from "./routes/oldspare.routes.js";
import wishlistRoutes from "./routes/wishlist.routes.js";
import searchRoutes from "./routes/search.routes.js";
import buyRequestRoutes from "./routes/userbuyrequest/buyrequest.routes.js";
import orderRoutes from "./routes/order.routes.js";
import sellPropertyRoutes from "./routes/sellproperty.routes.js";
import userPropertyRoutes from "./routes/property/user.property.routes.js";
import adminPropertyRoutes from "./routes/property/admin.property.routes.js";
import locationRoutes from "./routes/location.routes.js";
import linkRoutes from "./routes/link.routes.js";
import notificationRoutes from "./routes/notification.route.js";
import testimonialRoutes from "./routes/testimonial.route.js";
import storyRoutes from "./routes/story.route.js";
import youtubeAuthRoutes from "./routes/youtubeAuth.routes.js";
import recentlyViewedRoutes from "./routes/recently.viewed.routes.js";
import leadRoutes from "./routes/leads/lead.routes.js";
import commonSearchRoute from "./routes/common.search.route.js";
import surveyRoutes from "./routes/property/survey/survey.routes.js";
dotenv.config();
const app=express(),server=http.createServer(app);
export const io=new Server(server,{cors:{origin:"*",methods:["GET","POST","PUT","DELETE"]}});
const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename);
app.use(cors({origin:"*",methods:["GET","POST","PUT","DELETE","OPTIONS"],allowedHeaders:["Content-Type","Authorization"]}));
app.options("*",cors());
app.use(express.json({limit:"30mb"}));
app.use(express.urlencoded({extended:true}));
app.use(express.static(path.join(__dirname,"../public")));
app.get("/privacy-policy",(req,res)=>res.sendFile(path.join(__dirname,"../public/privacy-policy.html")));
app.get("/terms",(req,res)=>res.sendFile(path.join(__dirname,"../public/terms-and-conditions.html")));
app.get("/refund-policy",(req,res)=>res.sendFile(path.join(__dirname,"../public/refund-cancellation-policy.html")));
app.use("/",youtubeAuthRoutes);
connectDB().then(()=>{console.log("✅ MongoDB Connected");createAdminUser();}).catch(err=>{console.error("❌ MongoDB Error:",err);process.exit(1);});
app.use("/api/auth",authRoutes);
app.use("/api/users",userRoutes);
app.use("/api/admin",adminUserRoutes);
app.use("/api/reports",reportRoutes);
app.use("/api/chat",chatRoutes);
app.use("/api/carbrands",carBrandRoutes);
app.use("/api/carmodels",carModelRoutes);
app.use("/api/carvariants",carVariantRoutes);
app.use("/api/oldspare",oldSpareRoutes);
app.use("/api/mobile-brands",mobileBrandRoutes);
app.use("/api/laptop-brands",laptopBrandRoutes);
app.use("/api/pc-brands",pcBrandRoutes);
app.use("/api/electronics",userElectronicsRoutes);
app.use("/api/electronics/admin",adminElectronicsRoutes);
app.use("/api/bikebrands",bikeBrandRoutes);
app.use("/api/bikemodels",bikeModelRoutes);
app.use("/api/bikevariants",bikeVariantRoutes);
app.use("/api/cars/admin",adminCarRoutes);
app.use("/api/cars",(req,res,next)=>req.method==="POST"&&req.path==="/add"?adminCarRoutes(req,res,next):next());
app.use("/api/cars",userCarRoutes);
app.use("/api/bikes/admin",adminBikeRoutes);
app.use("/api/bikes",(req,res,next)=>req.method==="POST"&&req.path==="/add"?adminBikeRoutes(req,res,next):next());
app.use("/api/bikes",bikeRoutes);
app.use("/api/search",searchRoutes);
app.use("/api/buyrequest",buyRequestRoutes);
app.use("/api/wishlist",wishlistRoutes);
app.use("/api/orders",orderRoutes);
app.use("/api/sellproperty",sellPropertyRoutes);
app.use("/api/properties/admin",adminPropertyRoutes);
app.use("/api/properties",userPropertyRoutes);
app.use("/api/locations",locationRoutes);
app.use("/api/links",linkRoutes);
app.use("/api/notifications",notificationRoutes);
app.use("/api/testimonials",testimonialRoutes);
app.use("/api/stories",storyRoutes);
app.use("/api/leads",leadRoutes);
app.use("/api",commonSearchRoute);
app.use("/api",recentlyViewedRoutes);
app.use("/api/survey",surveyRoutes);
app.get("/api/app/version",(req,res)=>res.json({latest_version:"1.0.1",force_update:false,update_url:"https://play.google.com/store/apps/details?id=com.re2buy.app"}));
app.get("/",(req,res)=>res.status(200).json({success:true,message:"🚀 REBUY Backend API running successfully"}));
app.use((req,res)=>res.status(404).json({success:false,message:"API route not found"}));
app.use((err,req,res,next)=>{console.error("❌ Server Error:",err);res.status(500).json({success:false,message:err?.message||"Internal server error"});});
io.on("connection",socket=>{console.log("🟢 Socket Connected:",socket.id);socket.on("join",userId=>{socket.join(userId);console.log(`User Joined: ${userId}`);});socket.on("join-admin",()=>{socket.join("admin");console.log("👨‍💼 Admin Joined");});socket.on("disconnect",()=>console.log("🔴 Socket Disconnected"));});
const PORT=process.env.PORT||5000;
server.listen(PORT,()=>{console.log(`✅ Server running on port ${PORT}`);console.log("📍 Car Brands API: /api/carbrands");console.log("📍 Car Models API: /api/carmodels");console.log("📍 Car Variants API: /api/carvariants");console.log("📍 Admin Add Car: POST /api/cars/add");console.log("📍 Admin Cars: /api/cars/admin");console.log("📍 User Cars: /api/cars");console.log("📍 Bike Brands API: /api/bikebrands");console.log("📍 Bike Models API: /api/bikemodels");console.log("📍 Bike Variants API: /api/bikevariants");console.log("📍 Mobile Brands API: /api/mobile-brands");console.log("📍 Laptop Brands API: /api/laptop-brands");console.log("📍 PC Brands API: /api/pc-brands");console.log("📍 User Electronics API: /api/electronics");console.log("📍 Admin Electronics API: /api/electronics/admin");console.log("📍 User Property API: /api/properties");console.log("📍 Admin Property API: /api/properties/admin");console.log("📍 Orders API: /api/orders");console.log("📍 My Orders: GET /api/orders/my");console.log("📍 Create Order: POST /api/orders");console.log("📍 Survey API: /api/survey");console.log("📍 Add Survey: POST /api/survey/add");});